package main

import (
 "database/sql"
 "encoding/json"
 "fmt"
 "net/http"
 "strconv"
 "strings"
)

func sqlIdent(s string) string { return `"`+strings.ReplaceAll(s,`"`,`""`)+`"` }
func adminSchemaTable(r *http.Request) (string,bool) { t:=strings.TrimSpace(r.URL.Query().Get("table")); if t=="" || !validSchemaName(t){return "",false}; var ok bool; if userDB==nil{return "",false}; if e:=userDB.QueryRow(`SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=$1 AND table_type='BASE TABLE')`,t).Scan(&ok);e!=nil||!ok{return "",false};return t,true }
func validSchemaName(s string) bool { if len(s)==0||len(s)>63{return false};for _,r:=range s{if !(r=='_'||(r>='a'&&r<='z')||(r>='A'&&r<='Z')||(r>='0'&&r<='9')){return false}};return true }
func schemaColumns(table string)([]string,error){rows,e:=userDB.Query(`SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1 ORDER BY ordinal_position`,table);if e!=nil{return nil,e};defer rows.Close();var out []string;for rows.Next(){var c string;if e:=rows.Scan(&c);e!=nil{return nil,e};out=append(out,c)};return out,rows.Err()}
func schemaColumnMap(table string)(map[string]bool,error){cs,e:=schemaColumns(table);if e!=nil{return nil,e};m:=map[string]bool{};for _,c:=range cs{m[c]=true};return m,nil}
func schemaIdentityColumns(table string)([]string,error){rows,e:=userDB.Query(`SELECT a.attname FROM (SELECT i.indrelid,i.indkey,i.indnkeyatts FROM pg_catalog.pg_index i JOIN pg_catalog.pg_class t ON t.oid=i.indrelid JOIN pg_catalog.pg_namespace n ON n.oid=t.relnamespace WHERE n.nspname='public' AND t.relname=$1 AND i.indisvalid AND (i.indisprimary OR i.indisunique) AND i.indpred IS NULL AND i.indexprs IS NULL AND 0 <> ALL(i.indkey) ORDER BY i.indisprimary DESC,i.indnkeyatts,i.indexrelid LIMIT 1) chosen CROSS JOIN LATERAL unnest(chosen.indkey) WITH ORDINALITY key(attnum,position) JOIN pg_catalog.pg_attribute a ON a.attrelid=chosen.indrelid AND a.attnum=key.attnum WHERE key.position<=chosen.indnkeyatts ORDER BY key.position`,table);if e!=nil{return nil,e};defer rows.Close();var out []string;for rows.Next(){var column string;if e:=rows.Scan(&column);e!=nil{return nil,e};out=append(out,column)};return out,rows.Err()}
func completeSchemaIdentity(table string,where map[string]any)(bool,error){columns,e:=schemaIdentityColumns(table);if e!=nil{return false,e};if len(columns)==0||len(where)!=len(columns){return false,nil};for _,column:=range columns{value,ok:=where[column];if !ok||value==nil{return false,nil}};return true,nil}
func adminSchemaDataHandler(w http.ResponseWriter,r *http.Request){if !requireAdmin(w,r){return};w.Header().Set("Content-Type","application/json");table:=strings.TrimSpace(r.URL.Query().Get("table"));if table==""{rows,e:=userDB.Query(`SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE' ORDER BY table_name`);if e!=nil{http.Error(w,e.Error(),500);return};defer rows.Close();tables:=[]string{};for rows.Next(){var t string;if rows.Scan(&t)==nil{tables=append(tables,t)}};_=json.NewEncoder(w).Encode(map[string]any{"status":"success","schema":"public","tables":tables});return};if !validSchemaName(table){http.Error(w,"Invalid table",400);return};var exists bool;if e:=userDB.QueryRow(`SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=$1 AND table_type='BASE TABLE')`,table).Scan(&exists);e!=nil||!exists{http.Error(w,"Table not found",404);return};cr,e:=userDB.Query(`SELECT column_name,data_type,is_nullable,is_generated,COALESCE(identity_generation,'') FROM information_schema.columns WHERE table_schema='public' AND table_name=$1 ORDER BY ordinal_position`,table);if e!=nil{http.Error(w,e.Error(),500);return};defer cr.Close();type Col struct{Name string `json:"name"`;Type string `json:"type"`;Nullable string `json:"nullable"`;Generated string `json:"generated"`;IdentityGeneration string `json:"identity_generation"`};cols:=[]Col{};for cr.Next(){var c Col;if cr.Scan(&c.Name,&c.Type,&c.Nullable,&c.Generated,&c.IdentityGeneration)==nil{cols=append(cols,c)}};identityColumns,e:=schemaIdentityColumns(table);if e!=nil{http.Error(w,e.Error(),500);return};bigInts:=map[string]bool{};for _,column:=range cols{if column.Type=="bigint"{bigInts[column.Name]=true}};limit:=200;if n,e:=strconv.Atoi(r.URL.Query().Get("limit"));e==nil&&n>0&&n<=500{limit=n};q:=fmt.Sprintf("SELECT * FROM %s LIMIT %d",sqlIdent(table),limit);rr,e:=userDB.Query(q);if e!=nil{http.Error(w,e.Error(),500);return};defer rr.Close();names,_:=rr.Columns();data:=[]map[string]any{};for rr.Next(){vals:=make([]any,len(names));ptrs:=make([]any,len(names));for i:=range vals{ptrs[i]=&vals[i]};if rr.Scan(ptrs...)!=nil{continue};row:=map[string]any{};for i,n:=range names{v:=vals[i];if b,ok:=v.([]byte);ok{if len(b)>4096{v=string(b[:4096])+" … [truncated]"}else{v=string(b)}};if bigInts[n]&&v!=nil{v=fmt.Sprint(v)};row[n]=v};data=append(data,row)};_=json.NewEncoder(w).Encode(map[string]any{"status":"success","schema":"public","table":table,"columns":cols,"rows":data,"row_limit":limit,"identity_columns":identityColumns})}
func adminSchemaWriteHandler(w http.ResponseWriter,r *http.Request){if !requireAdmin(w,r){return};w.Header().Set("Content-Type","application/json");if r.Method!=http.MethodPost{w.WriteHeader(405);return};table,ok:=adminSchemaTable(r);if !ok{http.Error(w,"Table not found",404);return};var in struct{Values map[string]any `json:"values"`;Where map[string]any `json:"where"`};if e:=json.NewDecoder(r.Body).Decode(&in);e!=nil||len(in.Values)==0{http.Error(w,"values are required",400);return};if len(in.Where)>0{complete,e:=completeSchemaIdentity(table,in.Where);if e!=nil{http.Error(w,e.Error(),500);return};if !complete{http.Error(w,"A complete primary or unique key is required",400);return}};cm,e:=schemaColumnMap(table);if e!=nil{http.Error(w,e.Error(),500);return};keys:=[]string{};args:=[]any{};ph:=[]string{};for k,v:=range in.Values{if !cm[k]{http.Error(w,"Invalid column: "+k,400);return};keys=append(keys,k);args=append(args,v);ph=append(ph,fmt.Sprintf("$%d",len(args)))};var q string;if len(in.Where)==0{q=fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s) RETURNING *",sqlIdent(table),joinIdents(keys),strings.Join(ph,","))}else{_,wp,wa,e:=buildWhere(in.Where,cm,len(args)+1);if e!=nil{http.Error(w,e.Error(),400);return};args=append(args,wa...);q=fmt.Sprintf("UPDATE %s SET %s WHERE %s RETURNING *",sqlIdent(table),setPairs(keys,1),wp)};var row map[string]any;rows,e:=userDB.Query(q,args...);if e!=nil{http.Error(w,e.Error(),500);return};defer rows.Close();if rows.Next(){names,_:=rows.Columns();vals:=make([]any,len(names));ptrs:=make([]any,len(names));for i:=range vals{ptrs[i]=&vals[i]};if rows.Scan(ptrs...)==nil{row=map[string]any{};for i,n:=range names{row[n]=vals[i]}}};if row==nil{http.Error(w,"No row returned",404);return};_=json.NewEncoder(w).Encode(map[string]any{"status":"success","row":row})}
func joinIdents(a []string)string{out:=make([]string,len(a));for i,v:=range a{out[i]=sqlIdent(v)};return strings.Join(out,",")}
func setPairs(a []string,start int)string{out:=make([]string,len(a));for i,v:=range a{out[i]=fmt.Sprintf("%s=$%d",sqlIdent(v),start+i)};return strings.Join(out,",")}
func buildWhereSQL(m map[string]any,cm map[string]bool,start int)string{keys:=make([]string,0,len(m));for k:=range m{keys=append(keys,k)};sortStrings(keys);out:=make([]string,len(keys));for i,k:=range keys{out[i]=fmt.Sprintf("%s=$%d",sqlIdent(k),start+i)};return strings.Join(out," AND ")}
func buildWhere(m map[string]any,cm map[string]bool,start int)([]string,string,[]any,error){keys:=make([]string,0,len(m));for k:=range m{if !cm[k]{return nil,"",nil,fmt.Errorf("invalid where column: %s",k)};keys=append(keys,k)};sortStrings(keys);args:=make([]any,0,len(keys));for _,k:=range keys{args=append(args,m[k])};return keys,buildWhereSQL(m,cm,start),args,nil}
func sortStrings(a []string){for i:=1;i<len(a);i++{for j:=i;j>0&&a[j]<a[j-1];j--{a[j],a[j-1]=a[j-1],a[j]}}}
func adminSchemaDeleteHandler(w http.ResponseWriter,r *http.Request){if !requireAdmin(w,r){return};w.Header().Set("Content-Type","application/json");if r.Method!=http.MethodPost{w.WriteHeader(405);return};table,ok:=adminSchemaTable(r);if !ok{http.Error(w,"Table not found",404);return};var in struct{Where map[string]any `json:"where"`};if e:=json.NewDecoder(r.Body).Decode(&in);e!=nil||len(in.Where)==0{http.Error(w,"where is required",400);return};complete,e:=completeSchemaIdentity(table,in.Where);if e!=nil{http.Error(w,e.Error(),500);return};if !complete{http.Error(w,"A complete primary or unique key is required",400);return};cm,e:=schemaColumnMap(table);if e!=nil{http.Error(w,e.Error(),500);return};keys:=make([]string,0,len(in.Where));for k:=range in.Where{if !cm[k]{http.Error(w,"Invalid column: "+k,400);return};keys=append(keys,k)};sortStrings(keys);args:=make([]any,len(keys));for i,k:=range keys{args[i]=in.Where[k]};q:=fmt.Sprintf("DELETE FROM %s WHERE %s RETURNING *",sqlIdent(table),buildWhereSQL(in.Where,cm,1));rows,e:=userDB.Query(q,args...);if e!=nil{http.Error(w,e.Error(),500);return};defer rows.Close();if !rows.Next(){http.Error(w,"No matching row",404);return};_=json.NewEncoder(w).Encode(map[string]any{"status":"success","deleted":true})}
func adminSchemaPageHandler(w http.ResponseWriter,r *http.Request){serveAdminPage(w,r,"admin-schema.html")}
func init(){http.HandleFunc("/admin/schema",adminSchemaPageHandler);http.HandleFunc("/admin/schema/data",adminSchemaDataHandler);http.HandleFunc("/admin/schema/write",adminSchemaWriteHandler);http.HandleFunc("/admin/schema/delete",adminSchemaDeleteHandler)}

var _ sql.NullString
